import Footer from "./component/footer";
import Header from "./component/header";
import "./import.css";
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="container">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
